# Generated by Django 6.0.3 on 2026-04-02 01:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GitHubPR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repo", models.CharField(max_length=255)),
                ("branch", models.CharField(max_length=255)),
                ("number", models.IntegerField(null=True)),
                ("url", models.URLField(null=True)),
                ("state", models.CharField(max_length=20, null=True)),
            ],
            options={
                "unique_together": {("repo", "branch")},
            },
        ),
    ]
