# Generated by Django 6.0.3 on 2026-05-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conversation_id", models.CharField(max_length=64, unique=True)),
                ("project", models.CharField(default="", max_length=512)),
                ("branch", models.CharField(default="", max_length=255)),
                ("blurb", models.CharField(default="", max_length=200)),
                ("first_timestamp", models.CharField(default="", max_length=64)),
                ("last_timestamp", models.CharField(default="", max_length=64)),
                ("message_count", models.IntegerField(default=0)),
                ("searchable_text", models.TextField(default="")),
                ("file_size", models.BigIntegerField(default=0)),
                ("file_mtime", models.FloatField(default=0)),
            ],
        ),
    ]
