# Generated by Django 6.0.3 on 2026-05-13 21:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_conversationindex"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GitHubPR",
            new_name="ForgePR",
        ),
    ]
