# Generated by Django 6.0.3 on 2026-05-28 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_rename_githubpr_to_forgepr"),
    ]

    operations = [
        migrations.CreateModel(
            name="CronJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_name", models.CharField(max_length=255)),
                ("repo", models.CharField(max_length=512)),
                ("cron_expression", models.CharField(max_length=100)),
                ("params", models.TextField(blank=True, default="")),
                ("enabled", models.BooleanField(default=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CronJobRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conversation_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                ("trigger_type", models.CharField(default="scheduled", max_length=10)),
                ("pid", models.IntegerField(blank=True, null=True)),
                (
                    "cronjob",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="api.cronjob",
                    ),
                ),
            ],
        ),
    ]
