# Generated by Django 6.0.3 on 2026-06-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_cronjob_cronjobrun"),
    ]

    operations = [
        migrations.AddField(
            model_name="forgepr",
            name="cached_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
