from django.urls import path
from api import views

urlpatterns = [
    path("", views.index),
    path("autolinks/", views.autolinks),
    path("autolinks", views.autolinks),
    path("github-repo/", views.github_repo),
    path("github-repo", views.github_repo),
    path("plans/", views.plans),
    path("plans", views.plans),
    path("plans/<str:plan_id>/", views.plan_detail),
    path("plans/<str:plan_id>", views.plan_detail),
    path("plans/<str:plan_id>/execute/", views.plan_execute),
    path("plans/<str:plan_id>/execute", views.plan_execute),
    path("skills/", views.skills_list),
    path("skills", views.skills_list),
    path("skills/<str:skill_id>/", views.skill_detail),
    path("skills/<str:skill_id>", views.skill_detail),
    path("conversations/", views.conversations),
    path("conversations", views.conversations),
    path("conversations/<str:conversation_id>/", views.conversation_detail),
    path("conversations/<str:conversation_id>", views.conversation_detail),
    path("terminal/run/", views.terminal_run),
    path("terminal/run", views.terminal_run),
    path("sessions/new/", views.session_new),
    path("sessions/new", views.session_new),
    path("sessions/resume/", views.session_resume),
    path("sessions/resume", views.session_resume),
]
